name: kooha_task

description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  retrofit: ^4.0.1
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.6
  fluttertoast: ^8.2.2
  flutter_riverpod: ^2.3.6
  hive_flutter: ^1.1.0
  dio: ^5.2.1+1

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.7
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBold.ttf
          weight: 700
